### ISSUE TITLE
postcss-hash use the inputted css to calc hash even if the inputted css includes and inlines other css files by `postcss-import`

### ISSUE THREAD

**Issue by saneyuki** [dacodekid/postcss-hash#2]
postcss-hash use the inputted css to calc hash even if the inputted css includes and inlines other css files by `postcss-import`

## Environment

- postcss-hash: 0.2.1
- postcss: 6.0.23
- postcss-import: 11.1.0

## Examples

There are some files:

```
a.css
b.css
````

### `a.css`

```css
@import './b.css';
```

### `b.css`

```css
.bar-foo {
	color: red;
}
```

### `postcss.config.js`

```javascript
// postcss.config.js
module.exports = (ctx) => ({
    plugins: {
    	'postcss-import': {},
        'postcss-hash': {
            algorithm: 'sha256',
            trim: 20,
            manifest: './manifest.json'
        },
    }
});
```

### generated code 

`.bar-foo` will be inlined by `postcss-import`

```css
.bar-foo {
	color: red;
}
```

## Steps to Reproduce

1. With the above environment, run postcss.
2. _step 1_ will generate the above _generated code_.

## Actual Result

[By the code](https://github.com/dacodekid/postcss-hash/blob/bf8c255777a1a3172021b5c5080660ec40243c33/index.js#L21), postcss-hash calcs based on `a.css`. Not based on the generated code.

This means that the hash will not change if I change `b.css` but I don't change `a.css`.

## Expected Result

The hash will change if I change `b.css`.

**Comment by brycewray** [comment]
I still observe the same behavior, even though I see it apparently was fixed by a merge in September, 2018. Is it dependent on the order in which this plugin is loaded in `postcss.config.js` (example below)? I tried it as the first item and see this behavior. I tried it as the last item and glitchy builds result online, despite good local test results.

```js
const path = require('path')

module.exports = {
  plugins: [
    require('postcss-hash')({
      // algorithm: "sha512", // default = "md5"
      trim: 20,
      manifest: './_data/manifest.json',
      name: ({dir, name, hash, ext}) => path.join(dir, name + '-' + hash + ext)
    }),
    require('postcss-import'),
    require('tailwindcss'),
    require('postcss-preset-env')({ stage: 1 }),
    require('postcss-clean'),
  ],
}
```
