### ISSUE TITLE
Example for setting custom name

### ISSUE THREAD

**Issue by skramstad** [dacodekid/postcss-hash#7]
Hi @keithamus.

Is it possible to provide an example for setting a custom name? and the dir option.

Now its 
```
{
  "main.css": "main.a80bb6bc4faf8fd.css"
}
```

But I would like i.e
```
{
  "css/build/main.css": "css/build/main.a80bb6bc4faf8fd.css"
}

```
Thanks!

**Comment by keithamus** [comment]
I don’t think this is possible right now. PRs always welcome though! 😉😏😁

**Comment by skramstad** [comment]
Ok. Thanks :)
